### ISSUE TITLE
File only have a ERROR status

### ISSUE THREAD

**Issue by Gilles-Clemenceau** [chrisjbillington/git_nautilus_icons#3] opened 2016-12-12 10:53 UTC
Hi there,
I'm interesting in your module, but it don't seem to work on the file.
The folder are ok, but for the file with debug :

IndexStatus.ERROR
WorktreeStatus.ERROR
MergeStatus.ERROR

To be able to use it, I need to put in in usr/share/nautilus-python/extensions, it won't work in my local.

**Comment by Gilles-Clemenceau** [comment] 2016-12-12 12:44
After many tests, it seems ok with file or folder, but only on the folder with the .git, not on the subfolder.

**Comment by chrisjbillington** [comment] 2016-12-12 17:06
Hi! Thanks for letting me know about the problem.

What version of nautilus are you using?

**Comment by Gilles-Clemenceau** [comment] 2016-12-15 08:41
I'm using the 3.20.3.
But that weird, today all the folder are working, I didn't touch anything.
Is there a sort of cache in nautilus ?

**Comment by Gilles-Clemenceau** [comment] 2016-12-16 07:25
& today it's only working with the first level of the git folder, it's strange.

**Comment by chrisjbillington** [comment] 2017-11-06 20:38
Sorry for the radio silence. Are you still having this problem?

I have a new Ubuntu install on a new machine with Nautilus 3.26 and am not able to reproduce any problems like this.

I did  notice I had a few undocumented dependencies that I have now added to the README, but I suppose you must have had them all if things worked for you at all.

**Comment by chrisjbillington** [comment] 2017-11-11 18:54
Closing due to inability to reproduce on latest version of Nautilus. Let me know if you're still having problems!

**Closed as completed by chrisjbillington** 2017-11-11 18:54 UTC
